### PR TITLE
Feature/party selection

### PR DESCRIPTION
**Pull request by forgehe**
#367 

I'd appreciate it if ppl test that it works on their devices as well. 
The tapping locations are quite close to each other, so I don't want any misclicks to occur.
I'm mainly concerned about phones with notches, as I don't have a way to test that. 
Confirmed to work on Samsung S9.

### CODE REVIEW

**Comment by forgehe** [comment]
Just ran into an issue, where if the selected party was already in use, the start quest click wouldn't register for some reason.
(Eg. AutoSkill uses Party 1, Party 1 is already the default. Start Quest Button doesn't register)
(Eg2. AutoSkill uses Party1, Party 2 is the default. Start Quest Button registers the click)

**Comment by reconman** [comment]
I didn't even know that you can click on the dots at the top!

Seems like a good solution, I'll test this soon.

**Comment by reconman** [comment]
@forgehe Can you check my corrections?

**Comment by forgehe** [comment]
Corrections and documentation looks good!

**Review by reconman — APPROVED** [review]

**Comment by forgehe** [comment]
Just had one occurance where it tapped to Party2, and 2nd tap to Party1 did not register. It may be a fluke, but I'm thinking it might occur more frequently on laggier devices.

**Pull request merged**
