### PR TITLE
Project Avalon

### PR DESCRIPTION
**Pull request by ryuga93**
A little attempt to implement @PokeGuys API to enhance the Lua script. Refer to the readme for some basic understanding. I'll update a more throughout readme and include the [Pendragon](https://github.com/sugi-chan/pendragon) RL algo once I got some more spare time.

### CODE REVIEW

**Comment by 29988122** [comment]
Cool as fuck. Impressive work, ryuga bro!

Although I hate to say this, I'm currently busy finding a research-oriented (ethereum) job at the moment..don't really have time to read the codes. 

Besides, I only have basic understandings of python, implemented(read: copypasted) Viterbi/HMM in py during gradschool freshman year.

Nevertheless, happy to see you back! 
: )

**Comment by ryuga93** [comment]
Well do expect me to MIA soon^TM, had some time to take a break from my work and do some hobby stuff.

**Comment by 29988122** [comment]
> 
> 
> Well do expect me to MIA soon^TM, had some time to take a break from my work and do some hobby stuff.

It's completely ok and normal - that's how we engineer do things. 
Side projects here and there : p

お疲れさまでした、マスター XD

**Comment by TryBane** [comment]
Have only taken a cursory glance. I still don't really understand what functionality this adds. It is a lot of information, I'll probably have to take a look at it more before I completely understand it.

**Comment by ryuga93** [comment]
I'll make a detailed doc soon. For now, you can have a look at [battle.lua#L141](https://github.com/ryuga93/Fate-Grand-Order_Lua/blob/23a511eb60943a3f200d1c0d1794d73b7e721074/modules/battle.lua#L141), where I change the currentStage update to interact with the API if `Use_Avalon = 1` in User Setting(REGION_REGULAR.lua).

In regular.lua, it will assign the path of either /avalon/fgoLua or /avalon/pendragon. fgoLua folder contains the current Lua code which I have factored out, and pendragon folder has the REST API.

Pendragon will send and return data to PC through REST API, where in the PC, an instance of Python is running as server, using Flask library. To have a quick glance on the Python code, start from /api/source/index.py. The current URL that works is [localhost:5000/battle/current-stage](https://github.com/ryuga93/Fate-Grand-Order_Lua/blob/23a511eb60943a3f200d1c0d1794d73b7e721074/api/source/index.py#L88), where it will perform OCR on the image and return digits.

**Comment by TryBane** [comment]
Now if I understand correctly, this will allow people to begin their scripts at any stage and have it act correctly based on the commands they listed correct?

Also, is it the case then that they will have to play on the computer? Or will they need a computer to use this functionality? I believe I understand that this is entirely optional to use, thus anyone who can't use a computer won't have an issue running this.

Will this improve recognition time as well? Just curious if this comes with a speedup, or possibly a slow down?

**Comment by ryuga93** [comment]
> Now if I understand correctly, this will allow people to begin their scripts at any stage and have it act correctly based on the commands they listed correct?

For now, yes. 

> Also, is it the case then that they will have to play on the computer? Or will they need a computer to use this functionality? I believe I understand that this is entirely optional to use, thus anyone who can't use a computer won't have an issue running this.

You can play on mobile devices, as long as you have a server hosting the Python API (cloud server such as AWS or locally using localhost). If you run it using a local network, you will need to find the ip address of the PC (most probably in the format of 192.168.x.x).

Yup, it is optional. You can turn it off in the region's setting lua file.

> Will this improve recognition time as well? Just curious if this comes with a speedup, or possibly a slow down?
It depends on the data size, network speed, and the PC's CPU/GPU capacity. For the stage recognition, I didn't notice significant slow downs, would say it's on par with Ankulua's template matching speed. In the case where future features might introduce slow downs, one could optimize the data format and the Python's recognition algorithms to achieve faster recognition

**Comment by potchy** [comment]
jesus flipping christ

**Comment by ryuga93** [comment]
Yup it will merge into the Avalon branch of this repo

**Comment by TryBane** [comment]
Still trying to take a look but it is a hefty update so it is taking a while.

**Comment by PokeGuys** [comment]
LGTM

**Comment by PokeGuys** [comment]
The API_KEY and calcHash can be removed if you are not going to do API metric.

**Comment by potchy** [comment]
WHY IS IT NOT MERGED IT

**Pull request merged**
