### PR TITLE
Resolution scaling refactor (((again)))

### PR DESCRIPTION
**Pull request by potchy**
AnkuLua's author included a few functions that help deal with different resolutions, so it's time to delete some of the code we've worked so hard for! yay? Again, I tested the `menu -> support -> battle -> result` flow in the following resolutions and everything is working perfectly.
- 812x375
- 1280x720
- 1792x828
- 2048x1536
- 2160x1080
- 2246x1080
- 2388x1668
- 2560x1440
- 2688x1242
- 2732x2048

This time it should also support notches, so if anyone has a device with one, please help test the script then share your results.

See the links below for details on the new functions:
http://ankulua.boards.net/thread/1243/set-script-area
http://ankulua.boards.net/thread/7/settings#autoGameArea
http://ankulua.boards.net/thread/7/settings#getGameArea
http://ankulua.boards.net/thread/7/settings#setGameArea

**Be sure to update AnkuLua to 8.2.0!**

### CODE REVIEW

**Comment by ryuga93** [comment]
@vit2657 Please try this new update for notch.

**Comment by aqer** [comment]
I just try this on TW server, but it stucks at support selection screen.
The notch is located at left side and the resolution of the screenshot is 2159*1080.
screenshot_20190112-012528

Device: zonfone 5z(ZS620kl) 2246*1080 
Ankulua version: 8.2.0

**Comment by potchy** [comment]
Are you sure you downloaded the code from my fork?
If yes, please try my latest commit and report back. A dialog with some debug info should appear.

screenshot_2019-01-11-18-31-32

**Comment by aqer** [comment]
Yep, I use codes from your branch resolution-scaling-refactor-again.
Here is the dialog on my phone.
screenshot_20190112-105844

**Comment by potchy** [comment]
I'm confused.
The borders on your screenshot look even (about 120px wide), even with a notch? Shouldn't the left border be a bit more wide than the right one? Can you take a picture of your cellphone with the game open? Does the code in the `master` branch work for you?

**Comment by aqer** [comment]
Screenshots are here. 
If you need more screenshots, just let me know.
screenshot_20190113-164604
screenshot_20190113-164649

**Comment by potchy** [comment]
Right, here are three versions of the scaling module for you to try:
[scaling-getGameArea().zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2753193/scaling-getGameArea.zip)
[scaling-getRealScreenSize().zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2753194/scaling-getRealScreenSize.zip)
[scaling-getRealScreenSize()-getGameArea().zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2753195/scaling-getRealScreenSize.-getGameArea.zip)

Please try each one of them.
Just replace the existing file in the `/modules` folder.
At least one should not get stuck in the support screen (I hope so).
Don't forget the screenshots! You'll know which is currently running by looking at the name of the dialog.

screenshot_2019-01-13-12-58-50
screenshot_2019-01-13-12-59-09
screenshot_2019-01-13-12-56-29

By the way, what is the Android version of that phone?

**Comment by aqer** [comment]
Android version of the phone is 8.0.0 and I start script from stage selection screen.

scaling-getGameArea stuck at stage select screen
screenshot_20190114-010341
screenshot_20190114-010415

scaling-getRealScreenSize and scaling-getRealScreenSize.-getGameArea stuck at support screen.
screenshot_20190114-010509
screenshot_20190114-010634
screenshot_20190114-010545

**Comment by potchy** [comment]
W H Y
I'll try to emulate a device with notch to see what's going on, but I won't promise anything.
For now, I'll merge this as is since it seems to be working on devices without notch.

**Comment by ryuga93** [comment]
Seems to me that `getRealScreenSize()` already excluded the notch, but since notch is still physically there, `autoGameArea(true)` will cause Ankulua to detect the notch and deduct 87px from 2159px. 

This means that the notch width was deducted twice: 2246 - 87 -87 = 2072

So in scaling-getRealScreenSize, try setting `autoGameArea(false)` and see how it goes.

**Comment by aqer** [comment]
I just try to set autoGameArea(false) with current trunk.
Start script from stage selection screen will stuck at support selection screen;
Start script from battle screen won't do any thing.

I notice the description of autoGameArea()
> autoGameArea(enable)
Some devices have cutout (notch). Normally, games don't use the cutout areas. But those cutout areas exists in the AnkuLua screenshot. This will cause the scripts' wrong behavior.
Android P has formal API to support cutout. The cutout height could be got.
Therefore, if the user's device is with cutout, suggest to upgrade the device to Android P and above.
With autoGameArea(true) setting, AnkuLua can detect the area excluding cutout area.
Strongly suggest to set immersive first according to the game's behavior, then set autoGameArea(true).

Read more: http://ankulua.boards.net/thread/7/settings#ixzz5cnQ1hFEG 

It says that Android P has formal API to support cutout and suggest to upgrade the device to Android P and above. 

Perhaps autoGameArea() uses the notch related API of Android P? Thus Android 8.0 doesn't support autoGameArea correctly.

My device is Android 8.0, not Android P(9.0). Maybe someone has android P machine with notch can test it.

**Comment by ryuga93** [comment]
autoGameArea is getting the notch width of your phone correctly. But the thing that bugs me is that your phone decided not to include the notch area in your FGO screenshot. In https://github.com/29988122/Fate-Grand-Order_Lua/issues/115 both users screenshots have a wider black bar on the notch side. I'm not sure is it due to Android version or not.

It could be that Ankulua sees the game area differently than your screenshots. So in `function scaling.ApplyAspectRatioFix()` of scaling-getRealScreenSize.zip, set `autoGameArea()` to false and change all the `getRealScreenSize()` to `getGameArea()`, and take the screenshot of the dialog.

Another thing that you can do is to take screenshot using Ankulua's `Region:save()`, but let's see the dialog first.

**Comment by ryuga93** [comment]
From https://github.com/29988122/Fate-Grand-Order_Lua/issues/162 we can rule out Android 8 as the cause. So I'm still curious about how Ankulua "sees" your screen without autoGameArea().

Currently here are the possible causes I can think of:

1. getRealScreenSize and getGameArea return different value without autoGameArea. Else the current trunk would have worked with you setting autoGameArea to false.
2. scaling-getRealScreenSize is actually working, but not the support scrolling (https://github.com/29988122/Fate-Grand-Order_Lua/issues/149). For this case I assumed that you have chosen "preferred" support mode. You can test it again from the battle screen instead.

**Comment by aqer** [comment]
Here are some screenshots for your information.

1. Current  trunk  with [scaling.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2770501/scaling.zip) and autoGameArea(true)
screenshot_20190119-162258

2. Current  trunk  with [scaling.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2770501/scaling.zip) and autoGameArea(false)
screenshot_20190119-162008

3. Current trunk with scaling.lua of [scaling-getRealScreenSize.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2753194/scaling-getRealScreenSize.zip), 
autoGameArea(false)
Change all the getRealScreenSize() in scaling.ApplyAspectRatioFix() to getGameArea().

```
function scaling.ApplyAspectRatioFix(scriptWidth, scriptHeight)
	setImmersiveMode(true)
	autoGameArea(false)
	
	local gameWithBorders = getGameArea()
	local gameWithoutBorders = CalculateGameRegionWithoutBorders(scriptWidth, scriptHeight, gameWithBorders:getX(), gameWithBorders:getY())

	dialogInit()
	local message = "getGameArea(): %ix%i\n"
	message = message .. "gameWithoutBorders: Region(%i, %i, %i, %i)\n"
	message = message:format(getGameArea():getX(), getGameArea():getY()
						   , gameWithoutBorders:getX(), gameWithoutBorders:getY(), gameWithoutBorders:getW(), gameWithoutBorders:getH())
	addTextView(message)
	dialogShow("scaling-getRealScreenSize()")

    setGameArea(gameWithoutBorders)
end
```

But the value looks werid.
screenshot_20190119-175228

**Comment by potchy** [comment]
@aqer I think I'll open a thread in AnkuLua's forum about this. Please download the following scripts:
[scripts.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2793635/scripts.zip)

For each of them, take **two** screenshots of the "Resolution" dialog, like you did the other day: one in-game and another in the home screen in portrait mode. If your Android launcher doesn't support portrait mode, you can use any other app that does, like Chrome or Telegram, it doesn't matter really. You'll end up with **four** screenshots total. Post them here. Also, don't forget to restart the script between each screenshot take.

**Comment by aqer** [comment]
@potchy Done, just tell me if you need more.

ankulua version: 8.2.0-pro2
phone: Zenfone 5z (ZS620KL)
android version: 8.0.0

autoGameArea(false):
screenshot_20190125-235550
screenshot_20190125-235652

autoGameArea(true):
screenshot_20190125-235721
screenshot_20190125-235739

**Comment by potchy** [comment]
Er, sorry. I said portrait, but I meant landscape. Do you mind retaking those?

**Comment by aqer** [comment]
I'm busy recently, sorry for the late reply.

Here are the screenshots.
The notch is located at left outside of these screenshots.

autoGameArea(false)
screenshot_20190128-222344
screenshot_20190128-222442

autoGameArea(true)
screenshot_20190128-222517
screenshot_20190128-222538

Current trunk code with getGameArea.zip
screenshot_20190128-222928

Current trunk code with getRealScreenSize.zip  
But it doesn't have highlight area?
screenshot_20190128-223019

**Comment by potchy** [comment]
Oh, right. Place `gameWithoutBorders:highlight()` on line 43.

**Comment by aqer** [comment]
ok, I add highlight for getRealScreenSize.zip and take its screenshot.

Here are the screenshots.
The notch is located at left side beyond these screenshots.

autoGameArea(false)
screenshot_20190128-222344
screenshot_20190128-222442

autoGameArea(true)
screenshot_20190128-222517
screenshot_20190128-222538

Current trunk code with getGameArea.zip
screenshot_20190128-222928

Current trunk code with getRealScreenSize.zip  
screenshot_20190129-205100

**Comment by potchy** [comment]
@aqer 

Okay, I got the thread ready. Before I post it, can you test this `scaling.lua` just one more time to confirm one hypothesis of mine? [scaling.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2815282/scaling.zip)

At line 49, I hardcoded the region that supposedly should work on your device.
X coordinate is ((2246 [screen width] - 1920 [game width] - 87 [notch]) / 2) + 87 [notch] = 207.

**Comment by aqer** [comment]
@potchy 
I use current code with [scaling.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2815282/scaling.zip)
It shows error:
screenshot_20190201-010621
screenshot_20190201-010636

**Comment by potchy** [comment]
Er, sorry. The correct values for you to try are `Region(207,0,1920,1080)` and `Region(120,0,1920,1080)`.

**Comment by aqer** [comment]
I have test both Region(207,0,1920,1080) and Region(120,0,1920,1080) with starting script from menu and battle screen separately, but all four scenario can't work.
Starting script from menu screen will both stuck at support screen;
Starting script from battle screen won't do anything.

**Comment by aqer** [comment]
@potchy Done, I also take screenshots in game.

Region(120,0,1920,1080)
screenshot_20190202-145134
screenshot_20190202-145218
Region(207,0,1920,1080)
screenshot_20190202-145256
screenshot_20190202-145311

**Comment by potchy** [comment]
I give up. ヾ(￣o￣;)
http://ankulua.boards.net/thread/1359/getrealscreensize-weird-behavior-zenfone-zs620kl

**Comment by potchy** [comment]
Let's wait for the author's response first.

**Comment by aqer** [comment]
@potchy 

Done, I also take screenshots that notch is located at the right side.
It looks like some highlight region may the correct working region?
Additionally, I don't find images in/sdcard/AnkuLua/captured_images after I execute CaptureTest.lua.

Region(120,0,1920,1080).lua The notch is located at the left side.
screenshot_20190203-173249
screenshot_20190203-173410

Region(120,0,1920,1080).lua The notch is located at the right side.
screenshot_20190203-173455
screenshot_20190203-173517

Region(207,0,1920,1080).lua The notch is located at the left side.
screenshot_20190203-173550
screenshot_20190203-173622

Region(207,0,1920,1080).lua The notch is located at the right side.
screenshot_20190203-173641
screenshot_20190203-173657

**Comment by potchy** [comment]
Hmm, setting the script dimension actually did something.
Okay, I think I got it. Now, try the code from this branch:
https://github.com/potchy/Fate-Grand-Order_Lua/tree/notch-fix

**Comment by aqer** [comment]
The behavior of [https://github.com/potchy/Fate-Grand-Order_Lua/tree/notch-fix](https://github.com/potchy/Fate-Grand-Order_Lua/tree/notch-fix) branch still unchanged. 
Starting script from menu screen will both stuck at support screen;
Starting script from battle screen won't do anything.

**Comment by potchy** [comment]
I think we're getting closer, though.
Try my latest commit of that branch.

Upload a screenshot from here:
screenshot_2019-02-03-21-33-45

Click OK, then ignore this error:
screenshot_2019-02-03-21-33-53

Upload the screenshots created in `/sdcard/AnkuLua/captured_images`.
Try to look in the internal memory if you can't find them in your SD card.
screenshot_2019-02-03-21-28-54

**Comment by aqer** [comment]
The screenshot from latest commit is here.
screenshot_20190204-154523

I don't have SD card on the phone, 
and I still can't find screenshots on internal memory(\內部共用儲存空間\AnkuLua\captured_images) after I execute FGO_TW_REGULAR.lua.

**Comment by potchy** [comment]
Nevermind that then. Now try to update your Android and let's see what happens.

**Comment by aqer** [comment]
@potchy 

After I update OS to Android 9, I test the latest commit of main repository.
Everything works well with the notch at left or right side except that the scrolling speed of support screen is very slow. At least it works now :)

**Comment by potchy** [comment]
That's great! The scrolling speed is like that because it's the only way to work both in Daemon and Accessibility mode. Do you mind to take screenshots with the code from the notch-fix branch again, just so I can report back to the author?

**Comment by potchy** [comment]
Thanks. Glad this is finally solved. 😌

**Comment by aqer** [comment]
Finally, I can use my phone to instead of nox when I can't access my computer. Thanks bro!😁

**Pull request merged**
