### PR TITLE
Resolution scaling code refactor

### PR DESCRIPTION
**Pull request by potchy**
I'm home, guys! ╭( ･ㅂ･)و
This time I took @TryBane's code on a trip to refactoring land. Here's what I got:

### Goal
My goal with this refactoring was to eliminate the need to write `+ xOffset, + yOffset` to every location/region. Now, they are all stored in a table in `game.lua` and we simply loop over it to apply the offsets. Modules that depend on those locations/regions can do a `local game = require("game")`.

### Code
The code in `scaling.lua` is slightly more verbose, but I believe that what it is doing is more clear now.
You'll notice that I structured `game.lua`, `scaling.lua` and `math-utils.lua` differently from the "older" modules, like `support.lua`. I mean, like this:

```lua
local mathUtils = {}

function mathUtils.Truncate(number)
    local decimal_places = number % 1
    return number - decimal_places
end

return mathUtils
```

Instead of:
```lua
local function Truncate(number)
    local decimal_places = number % 1
    return number - decimal_places
end

return {
    Truncate = Truncate
}
```

The reason is that I sometimes declare a function that I want to be visible outside of a module and then I forget to put it in the table at the end of the file (lol). Also, **we** sometimes forget to put a forward declaration when adding new functions. You thought I had missed [this heresy of yours](https://github.com/29988122/Fate-Grand-Order_Lua/commit/b5c1e1edb636e7902ed44460cacb15f7e714cf3b#diff-ca935c4285f003a3073dbd7878d8bb53R175), @29988122?! Well, I didn't! <sub><sub>i'm joking pls don't ban me</sub></sub>

Anyway, dealing with these issues is annoying, so let's just do what's easier for us.
We can apply this style to the other modules later.

### Naming conventions (again)
Uh, you may have noticed that the constants in `game.lua` are not really constants anymore because they can be changed to apply the offsets. Do we leave them as is or do we change them back to PascalCase?

### Tests
I've used Nox to test the `menu -> support -> battle -> result` flow in different resolutions.
Everything is working great in all of them, even the MLB CE detection which is extra sensible to positioning. Here are the results, just to document:
- [812x375](https://user-images.githubusercontent.com/4316326/50726413-d9484400-10f3-11e9-86a7-1f30700c426a.png)
- [1280x720](https://user-images.githubusercontent.com/4316326/50726414-d9e0da80-10f3-11e9-95d9-ea72559e7c68.png)
- [1792x828](https://user-images.githubusercontent.com/4316326/50726415-d9e0da80-10f3-11e9-9bf1-5ab54f616159.png)
- [2048x1536](https://user-images.githubusercontent.com/4316326/50726416-da797100-10f3-11e9-866f-7791be0745eb.png)
- [2160x1080](https://user-images.githubusercontent.com/4316326/50726417-da797100-10f3-11e9-9cd4-6d99b5b778c7.png)
- [2246x1080](https://user-images.githubusercontent.com/4316326/50726418-db120780-10f3-11e9-8236-f0062aa469e6.png)
- [2388x1668](https://user-images.githubusercontent.com/4316326/50726419-dcdbcb00-10f3-11e9-9c13-ab178d200eb1.png)
- [2560x1440](https://user-images.githubusercontent.com/4316326/50726420-dcdbcb00-10f3-11e9-9d34-1ce490d013e9.png)
- [2688x1242](https://user-images.githubusercontent.com/4316326/50726421-dcdbcb00-10f3-11e9-93d2-c4f5f5098d2d.png)
- [2732x2048](https://user-images.githubusercontent.com/4316326/50726422-dd746180-10f3-11e9-9f28-573b6281ced1.png)

### Notches?
After reading #148 thoroughly, it seems that the only unsolved issue is the extra offset the game uses when the device has a notch. ~jesus christ why did phone manufacturers create this ugly thing?~

### CODE REVIEW

**Comment by potchy** [comment]
There's a conflict introduced in 373f76c8b4e4f6a8052157686e89ac162cb76aed, but I will fix it after we decide to merge this pull request.

**Comment by 29988122** [comment]
Oh, that was neat! (Dunno what to say besides this XD)

**Comment by ryuga93** [comment]
@29988122 The God of Code Design & Styling

**Comment by TryBane** [comment]
I like it. Much more scalable than what I did and glad I could help with the figuring out of how to get an offset that works. Also a quick note regarding what may actually allow us to figure out notch is comparing the AppUsableScreenSize with RealScreenSize because they actually return different values when a notch is present. Non-standard aspect ratios normally work fine with AppUsableScreenSize but the notch fucks it up. So, this might be the key. I haven't figured it all out yet though. Also, welcome home @potchy!

**Comment by Zaein** [comment]
Potchy, just wanted to let you know that the scrolling is working for me.

If its any consolation I am using a Note 8 with the most updated version of the android software,

**Comment by potchy** [comment]
Okay, so I guess this is ready to merge.
Any input on the naming conventions though? Q_Q

**Comment by Zaein** [comment]
> Any input on the naming conventions, though?  Q_Q

Name the variables after your favorite waifus.

**Comment by potchy** [comment]
good idea for a cipher algorithm

**Comment by Zaein** [comment]
Hey man, as long as you all know what they do it'd be a okay ;)

**Comment by TryBane** [comment]
While I think variable names of waifus is actually very creative, I'd rather not keep a list on hand of what each waifu represents unless you can create some sort of logic determination to derive it's representation from the name itself :D 

Aside from that I think merging is a-okay. You can either make the adjustment to support the other scripts with the scaling solution or I can make that adjustment myself.

**Comment by ryuga93** [comment]
Well in the scope of game.lua they are still constants so I think it's fine. I'll go ahead and merge it.

**Comment by gn01791992** [comment]
Can you please test the resolution at 3120*1440? I use Mate20 Pro, I can't select a friend after running the script, and it stops at that step, I tried to re-screen and replace it. But it didn't improve.

And in the battle, sometimes there will be mistakes in the battle round, so the skills are confused.

So guess is the problem of abnormal resolution? Please help test it.
The resolution of the script is improving, thank you for the teamwork!

**Comment by potchy** [comment]
Your device has a notch (that ugly thing with the camera partially covering the screen) and that's currently unsupported. See #148 for details and a workaround @Trybane suggested.

**Comment by cboldes** [comment]
By chance is the Samsung Galaxy S10+ causing any issues with this? I can run JP just fine but EN seems to not be working properly. If need be I am able to help test out!  @potchy @TryBane

**Comment by Zaein** [comment]
My issues were with the Note 9 and, with Trybanes help, I was able to
resolve them. There were still issues with auto gift and auto friend but I
was able to sort those issues out myself.

If you're using a Note 10 there will likely be issues as the screen is
actually smaller than the Note 9.

I play the English version.

**Comment by cboldes** [comment]
@Zaein I actually have the Note 10+. What did you do by chance? I play on the English version also.

**Comment by Zaein** [comment]
Oh, I think the 10+ screen is larger.

In the game files you can specify the X and Y coordinates. This is easy for
the auto friend and lottery but much more difficult for the main script.
You will want to get help from one of the developers for that.

**Comment by cboldes** [comment]
@Zaein did you get ahold of them through here? Or by different methods.

**Comment by Zaein** [comment]
Yeah, they just responded to one of my posts.

**Comment by cboldes** [comment]
@cboldes who was it by chance? 🤔

**Pull request merged**
