### PR TITLE
Document Support Image Maker script

### PR DESCRIPTION
**Pull request by MathewSachin**
Hope I did it right. Let me know if there are any changes to make.

@reconman

### CODE REVIEW

**Comment by reconman** [comment]
@MathewSachin I've made some small corrections, thank you very much for your work so far.

**Comment by MathewSachin** [comment]
Well, I'd like to thank you all for your work on this script too.
Really eases the grind.

I also tried porting the whole script along with features of AnkuLua as an app too: https://github.com/MathewSachin/Fate-Grand-Automata. Didn't want to advertise it or anything. The app I made works fine for me but might not be good enough for general use. And it's a pain to debug.

Just wanted to tell you that Support Image Maker came from there.
Still, the credit is to you guys for your awesome work on this script.
I'd try to keep contributing whenever I have the opportunity to.

**Comment by MathewSachin** [comment]
Also, let me know if there are any features I can try working on. I can test only on NA version but I want to help if I can.

**Comment by reconman** [comment]
FGO automation without a paid subscription sounds nice, and I like C# much more than Lua, although I don't have much experience with C# and no experience with Android apps.

Too bad the Ankulua core scripts are closed source, so you have to guess how they've implemented new features.

I'll probably take a look at your app soon.

There's one thing I wanted to mention regarding this feature. I hoped it would work in the Friend List, but sadly it's off by a few pixels for both the Servant and CE images.

Since the Friend List screen probably looks different on JP than on NA, I gave up on correcting the script. (Let the user decide between Support Selection and Friend List)

**Comment by MathewSachin** [comment]
We might be able to check which screen we are on, whether we are on support selection screen or on friend list screen and then use the corresponding region.
I'll give this a try later and let you know.

**Pull request merged**
