### PR TITLE
Why is this here?

### PR DESCRIPTION
**Pull request by TryBane**
Looking into the issue regarding Support scrolling, and I'm not sure why this is here. In any case where the support items aren't found, it should return nil, and in the case where it returns nil, it'll scroll further. And when it hits the bottom, it still shouldn't crash.

### CODE REVIEW

**Comment by potchy** [comment]
It's in there to indicate that a servant/CE was found out of the expected bounds, i.e. either `scrollList()` is miscalibrated (#206) or `SUPPORT_LIST_ITEM_REGION_ARRAY` needs some adjustments or the coordinates got misaligned because of the notch calculations and stuff. It's complicated. See:

#106 
https://raw.githubusercontent.com/29988122/Fate-Grand-Order_Lua/master/docs/support_list_item_regions_top.png
https://raw.githubusercontent.com/29988122/Fate-Grand-Order_Lua/master/docs/support_list_item_regions_bottom.png

I'm fine with "fixing" the error, but you should replace it for a toast, instead of removing it altogether. This way, it will still indicate that there's something wrong instead of failing silently.

**Comment by TryBane** [comment]
But it isn't really failing due to any issue with the script, it is failing due to something akin to lag that is probably the result of Media Projection (as I haven't seen this issue occur much at all from android 7.0 and lower)

A toast would probably be fine, but when the image is present but not within the bounds because of a notch, it does fail with that error, it sits there and does nothing. The only time this error occurs is if the Servant is found at the bottom but due to the space the CE can't be checked. And then what results is this error, even though after scrolling it would be able to see if the CE is there afterwards. I have yet to see another instance of this case coming up in another scenario.

**Comment by potchy** [comment]
These 3rd and 4th regions should account for the bottom of the list.
If it's not working then there is definitely something wrong.

https://raw.githubusercontent.com/29988122/Fate-Grand-Order_Lua/master/docs/support_list_item_regions_bottom.png

**Comment by potchy** [comment]
If it's lagging that much, try to tweak the wait time here:
https://github.com/29988122/Fate-Grand-Order_Lua/blob/231971110b2f5de334b92ddcd7b4f6d54068a23d/modules/support.lua#L170

**Comment by TryBane** [comment]
The issue the lag causes isn't a recognition issue but rather an issue in how far it ends up scrolling. The lag disrupts the scroll distance causing the menu to not scroll enough and thus disaligns the servants found from the region array provided. I believe an alternative to the region array would be to create the bounds dynamically after it recognizes the servant. I will look into this, but I do realize why this error message exists.

I believe I have come up with a solution just now. I will see about implementing it in a couple of hours (if you'll still be on to double check my work)

**Comment by potchy** [comment]
If you disregard the region array and calculate the distance to the CE dynamically while assuming that `scrollList()` is inconsistent, which is what I tried to do while writing this module for the first time, you'll also run into the problem of some servants/CEs being skipped and you'll need to scroll up/down accordingly, otherwise the script would never select those.

**Comment by TryBane** [comment]
Actually, I was going to dynamically create the regions myself. I'd maintain the same exact usage, but by creating the regions dynamically after the scroll finishes each time, it won't run into an issue where they don't align with the servant options, thus eliminating the need for the exit message.

But, I'll run down what I plan to do. I am going to make a small image that is searched for that will determine the location a support (I can use the Quick card icon on the right side) and the from the location of that image I can extrapolate the entire segment, thus creating the region. Then I can make a duplicate above or below the one already made based on whether it would go out of bounds or not.

Then I can use these two regions (only 2 will ever be able to be made) to create the array used in the current search formula.

As a result, we can remove the error message and still be able to enjoy the search without any worries of lag causing an inconsistent scrolling issue or hitting the bottom of the friends list.

Due to the nature of the scrolling as it is right now, it should never scroll in such a way that a servant or CE is missed.

**Comment by TryBane** [comment]
@potchy Okay, I am pretty confident that this should work as intended. Give it a try and see if you are satisfied with this as a replacement.

**Comment by MatheusOPP** [comment]
I'm a beginner to GitHub so I'm not sure if this is supposed to be correct procedure, but I tried replicating the exact changes in the support.lua file to reflect the commits above, and copying the new image to its appropriate folder to try out this solution, since with the files that are currently in the master branch, I end up getting an error after the script runs for some time (around one hour or so) in the support screen that's the same as #229.

However, doing exactly that is giving me an error where after two swipes or so in the support screen, the script returns another error, every single time. I attached screenshots of the error below, if you want to check it.
error1
error2
error3

**Comment by TryBane** [comment]
You should have replaced the files as mistakes are bound to be made. Can you upload the file you have with the changes so I can take a look?

**Comment by MatheusOPP** [comment]
Sure. Had to zip it since GitHub doesn't let me attach it directly here, but here it is. Also put my "FGO_EN_REGULAR.lua" there just in case.
[support.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/3563303/support.zip)

**Comment by TryBane** [comment]
Okay, I see I see. I didn't consider that returning nil would break the search algorithm. Will have to fix that. I know of a way but can't do it till I get home. Give me about 30 minutes to solve this and if you could try again that would be awesome.

**Comment by TryBane** [comment]
@MatheusOPP Okay, change made. That should work as long as I didn't make a spelling mistake (which shouldn't be the case since I did copy paste....)

**Comment by potchy** [comment]
I liked your idea and I believe it will work great (will test right away), but now **I'm** the one who doesn't understand why this conditional exists.
https://github.com/29988122/Fate-Grand-Order_Lua/blob/383483c8ab2df53659ea2379e6d35b6edcce2364/modules/support.lua#L295-L296

Also, @MatheusOPP problem indicates that there's some scenario we didn't think of yet.
Your last commit (383483c) doesn't fix the problem. It's just swallowing the error and failing silently.
I'm not sure if it's related, but maybe you could this as an anchor instead, as it's closer to the top of the list item.

image

**Comment by TryBane** [comment]
I setup that conditional so that it doesn't return a support that has the CE hidden on the bottom. However, I realize that that won't work as well as needed for when people are just looking for the Servant so it probably shouldn't exist.

As for my commit to solve @MatheusOPP's problem, it occurred when searching for both a Servant and CE, but then the Servant was found on the bottom when the CE is hidden. When this occurs, it'll try to get the bounds and return it, however due to that conditional, it'll kick it out and return nil instead. My commit allows it to still return a bounds, just not one with the Servant or CE, and is on the top, which will nullify any "potential" false positive match with CEs due to the conditional that the CE be below the Servant found.

If we remove the conditional, then we probably don't need to have the latest commit either. Glad you like it too.

**Comment by MatheusOPP** [comment]
No sure if my input is still needed at this point but, I let it run for some hours now and it seems to be working perfectly. I'll let you know if anything strange happens later.

**Comment by potchy** [comment]
I think it's okay to merge this whenever you're ready. Just please read my previous comment again as I edited it multiple times and I'm not sure you got everything. lol
Nevertheless, I may revisit the search algorithm when I do get some free time. Work has been crazy this month.

**Comment by TryBane** [comment]
I see, I understand the last paragraph (which wasn't there when I commented I believe) but I don't believe it is necessary. It would probably work of course, but by removing the conditional it shouldn't be an issue (and should still allow us to remove the default return bounds). I'll go ahead and do that real quick and then merge.

**Comment by TryBane** [comment]
Also took your advice and made it toast in case it hits the default return, as something went wrong in that case.

**Pull request merged**
