### PR TITLE
Fix #340 and #341, update README with info about pre load NP

### LINKED ISSUE #340: NullPointer error on support selection
I can't understand which is the error here, other times it leds me to the images, but this time I don't know.
Screenshot_20200224-102152
Screenshot_20200224-031814

### LINKED ISSUE #341: Since last version, JP no longer works at all
I updated to the latest release, now when running the script it just draws red squares on the screen in three different locations. Doesn't select anything, doesn't do anything. Had to revert to an older release. Here's some screenshots of it drawing the squares.

image

image

image

The EN version of the script never ran on my Note 10+, but the JP version worked fine for a long time, until the latest major update of the script I guess. Now both the EN and JP version no longer work on either Note 10+ or Note 5. 

Here's a screenshot from the support screen on my Note 5, also just drawing the squares but not doing anything at all
image

Furthermore, choosing "first" as a support option throws null pointer exception like here
https://github.com/29988122/Fate-Grand-Order_Lua/issues/340

### PR DESCRIPTION
**Pull request by reconman**
Please see my notes in #340 and #341

### CODE REVIEW

**Comment by 29988122** [comment]
Judging by the comments, it seems that you probably know what you're doing & is capable of doing so. And you're of great help answering people's issues.

Since most of the current contributors are overwhelmed by their real life^tm, myself included, I think maybe you're willing to help people here, trying to support this codebase and people in your free time.

Would you like to be a collaborator for this repo? Even managing issues only (open, answer, close, label duplicate) is of great help for anyone who's using this script.

Of course, I'll have to ask others first.
@potchy  @ryuga93 @TryBane 
What's your take?

**Comment by reconman** [comment]
@29988122 First of all, I'm a professional Java programmer and have some experience with Git and Github through my contributions to the saltbot project, which is written in Typescript. I don't have experience with Lua and so far it seems really restrictive, but we can't do anything about it because of Ankulua.

I'm a bit stressed by work since most Pull Request I get there have lots of bugs or wrongly implemented features, but I still can manage to do a bit of Open Source programming in my free time.

I'd gladly accept the collaborator role, I would just need to know if there are any guidelines for handling Pull Requests related to code reviews. And I just found the naming conventions in CONTRIBUTING.md, so I will rename the debug_mode to Debug_Mode in this Pull Request. At least that's how I understood the naming rules.

**Comment by TryBane** [comment]
Thanks for fixing my mistake. I didn't realize the debug mode would cause an issue in JP since I had wholly forgotten about its existence (especially since I only ever used it to debug problems people had) so it never occurred to me it would cause a bug in the other versions.

Also, since I never use first for Support selection, I completely overlooked the affect deleting that click would have, so again thanks for fixing that.

If the guy is helping with fixing bugs or adding features, I have zero issues with him coming in as a collaborator. I haven't been able to help answer questions or even check the issues posted recently so I appreciate the help he has provided in that regard as well. Seems like he would be a good addition.

**Comment by reconman** [comment]
@TryBane One thing I wanted to mention is that the friend support selection using image detection is behaving weirdly after I updated to the new version. It doesn't detect any CE support matches without scrolling down. And it's going through the list much faster.

I will take a detailed look at the recent changes after I get home from work today.

**Comment by TryBane** [comment]
I have noticed this as well. I've been able to solve the issue somewhat by adjusting the similar() method used in Pattern, but there have been cases of false positives (which is what led me to make the original adjustment in the pull request prior). I think the current best option will be to reduce the similar value back to what it was, so that people have less issues in this regard.

**Comment by reconman** [comment]
@TryBane Can confirm, see my latest commit to revert your changes. A value of .8 will detect MLB CEs, .85 will not.

**Comment by TryBane** [comment]
Sounds good. I expect false positives will be a thing again at a later date, but this is unavoidable with the current format without making the userbase as a whole deal with problems.

**Comment by potchy** [comment]
I'm doing a merge commit again as I think your original commits each have meaningful messages and references to other issues. Thank you for your interest and help!

**Comment by reconman** [comment]
@29988122 @potchy Any update on the collaborator role? I would really like to add some labels to Issues and close some.

**Comment by potchy** [comment]
Oh, I think only @29988122 <sup><sup><sup>(please show up!)</sup></sup></sup> can assign roles, as I don't have access to the "Settings" pane.

image

**Comment by 29988122** [comment]
> 
> 
> Oh, I think only @29988122 (please show up!) can assign roles, as I don't have access to the "Settings" pane.
> 
> image

I thought you don't agree with that decision XD
Now I get it.

Collaborator role added, @reconman  助手よ存分に働け！(Work tirelessly to die, my assisstant!)

**Pull request merged**
